/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.IntegradorMVC.vista;

/**
 *
 * @author tomad
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuActas = new javax.swing.JMenu();
        jMenuItemGestionActa = new javax.swing.JMenuItem();
        jMenuItemNuevaActa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemVerAutoridades = new javax.swing.JMenuItem();
        jMenuItemNuevaAutoridad = new javax.swing.JMenuItem();
        jMenuConsultasReportes = new javax.swing.JMenu();
        jMenuItemReporteActa = new javax.swing.JMenuItem();
        jMenuItemActaPorConductor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 61, 77));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 48)); // NOI18N
        jLabel1.setText("Sistema de actas");

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel2.setText("Ultimas Infracciones:");

        jTable1.setBackground(new java.awt.Color(247, 250, 253));
        jTable1.setForeground(new java.awt.Color(247, 250, 253));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehiculo", "Conductor", "Tipo de Infraccion", "Autoridad"
            }
        ));
        jTable1.setSelectionForeground(new java.awt.Color(247, 250, 253));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 233, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(0, 233, Short.MAX_VALUE))
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/IntegradorMVC/imagenes/casa (2).png"))); // NOI18N
        jMenu3.setText("Home");
        jMenuBar1.add(jMenu3);

        jMenuActas.setText("Actas");

        jMenuItemGestionActa.setText("Gestión de Actas");
        jMenuItemGestionActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionActaActionPerformed(evt);
            }
        });
        jMenuActas.add(jMenuItemGestionActa);

        jMenuItemNuevaActa.setText("Nueva Acta");
        jMenuItemNuevaActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaActaActionPerformed(evt);
            }
        });
        jMenuActas.add(jMenuItemNuevaActa);

        jMenuBar1.add(jMenuActas);

        jMenu2.setText("Autoridades");

        jMenuItemVerAutoridades.setText("Ver Autoridades");
        jMenuItemVerAutoridades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerAutoridadesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVerAutoridades);

        jMenuItemNuevaAutoridad.setText("Nueva Autoridad");
        jMenu2.add(jMenuItemNuevaAutoridad);

        jMenuBar1.add(jMenu2);

        jMenuConsultasReportes.setText("Consultas/Reportes");

        jMenuItemReporteActa.setText("Reporte de Actas");
        jMenuConsultasReportes.add(jMenuItemReporteActa);

        jMenuItemActaPorConductor.setText("Buscar Acta por Conductor");
        jMenuItemActaPorConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActaPorConductorActionPerformed(evt);
            }
        });
        jMenuConsultasReportes.add(jMenuItemActaPorConductor);

        jMenuItem1.setText("Buscar Infracción por Vehículo");
        jMenuConsultasReportes.add(jMenuItem1);

        jMenuBar1.add(jMenuConsultasReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGestionActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionActaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGestionActaActionPerformed

    private void jMenuItemNuevaActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaActaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNuevaActaActionPerformed

    private void jMenuItemActaPorConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActaPorConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemActaPorConductorActionPerformed

    private void jMenuItemVerAutoridadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerAutoridadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemVerAutoridadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuActas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultasReportes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemActaPorConductor;
    private javax.swing.JMenuItem jMenuItemGestionActa;
    private javax.swing.JMenuItem jMenuItemNuevaActa;
    private javax.swing.JMenuItem jMenuItemNuevaAutoridad;
    private javax.swing.JMenuItem jMenuItemReporteActa;
    private javax.swing.JMenuItem jMenuItemVerAutoridades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
