/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.IntegradorMVC.vista;

import com.mycompany.IntegradorMVC.controlador.VistaPrincipalController;

/**
 *
 * @author tomad
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public VistaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuActas = new javax.swing.JMenu();
        gestionActaJMenuItem = new javax.swing.JMenuItem();
        nuevaActaJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        verAutoridadesJMenuItem = new javax.swing.JMenuItem();
        nuevaAutoridadJMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        rutasJMenuItem = new javax.swing.JMenuItem();
        vehiculosJMenuItem = new javax.swing.JMenuItem();
        organizacionesJMenuItem = new javax.swing.JMenuItem();
        tiposInfraccionesJMenuItem = new javax.swing.JMenuItem();
        tiposRutasJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 61, 77));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 48)); // NOI18N
        jLabel1.setText("Sistema de actas");

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 36)); // NOI18N
        jLabel2.setText("Ultimas Infracciones:");

        jTable1.setBackground(new java.awt.Color(247, 250, 253));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Renault", "Juan Perez", "Grave", "Genaro Ramirez"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehiculo", "Conductor", "Tipo de Infraccion", "Autoridad"
            }
        ));
        jTable1.setSelectionForeground(new java.awt.Color(247, 250, 253));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 233, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(0, 233, Short.MAX_VALUE))
                            .addComponent(jSeparator1))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\tomad\\Documents\\GitHub\\Integrador-MVC\\resources\\casa.png")); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenuActas.setText("Actas");
        jMenuActas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuActasActionPerformed(evt);
            }
        });

        gestionActaJMenuItem.setText("Gestión de Actas");
        gestionActaJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionActaJMenuItemActionPerformed(evt);
            }
        });
        jMenuActas.add(gestionActaJMenuItem);

        nuevaActaJMenuItem.setText("Nueva Acta");
        nuevaActaJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActaJMenuItemActionPerformed(evt);
            }
        });
        jMenuActas.add(nuevaActaJMenuItem);

        jMenuBar1.add(jMenuActas);

        jMenu2.setText("Autoridades");

        verAutoridadesJMenuItem.setText("Ver Autoridades");
        verAutoridadesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAutoridadesJMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(verAutoridadesJMenuItem);

        nuevaAutoridadJMenuItem.setText("Nueva Autoridad");
        jMenu2.add(nuevaAutoridadJMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Listas");

        rutasJMenuItem.setText("Rutas");
        jMenu1.add(rutasJMenuItem);

        vehiculosJMenuItem.setText("Vehiculos");
        jMenu1.add(vehiculosJMenuItem);

        organizacionesJMenuItem.setText("Organizaciones");
        jMenu1.add(organizacionesJMenuItem);

        tiposInfraccionesJMenuItem.setText("Tipos de Infracciones");
        tiposInfraccionesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposInfraccionesJMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(tiposInfraccionesJMenuItem);

        tiposRutasJMenuItem.setText("Tipos de Rutas");
        jMenu1.add(tiposRutasJMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionActaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionActaJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gestionActaJMenuItemActionPerformed

    private void nuevaActaJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActaJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevaActaJMenuItemActionPerformed

    private void verAutoridadesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAutoridadesJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verAutoridadesJMenuItemActionPerformed

    private void tiposInfraccionesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposInfraccionesJMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiposInfraccionesJMenuItemActionPerformed

    private void jMenuActasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuActasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuActasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem gestionActaJMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuActas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    public javax.swing.JMenuItem nuevaActaJMenuItem;
    public javax.swing.JMenuItem nuevaAutoridadJMenuItem;
    public javax.swing.JMenuItem organizacionesJMenuItem;
    public javax.swing.JMenuItem rutasJMenuItem;
    public javax.swing.JMenuItem tiposInfraccionesJMenuItem;
    public javax.swing.JMenuItem tiposRutasJMenuItem;
    public javax.swing.JMenuItem vehiculosJMenuItem;
    public javax.swing.JMenuItem verAutoridadesJMenuItem;
    // End of variables declaration//GEN-END:variables
}
